#!/usr/bin/env bash
# This script display the information about subdomains
# shellcheck disable=SC2086
my_func()
{
if [ "$#" -eq 2 ];
then
dig $2.$1 | grep -A1 'ANSWER SECTION' | awk -v subdomain=$2 'NR==2{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
else
dig "www".$1 | grep -A1 'ANSWER SECTION' | awk -v subdomain="www" 'NR==2{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
dig "lb-01".$1 | grep -A1 'ANSWER SECTION' | awk -v subdomain="lb-01" 'NR==2{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
dig "web-01".$1 | grep -A1 'ANSWER SECTION' | awk -v subdomain="web-01" 'NR==2{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
dig "web-02".$1 | grep -A1 'ANSWER SECTION' | awk -v subdomain="web-02" 'NR==2{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
fi
}

if [ "$#" -eq 2 ];
then
my_func "$1" "$2"
else
my_func "$1"
fi
