#!/usr/bin/env bash
# cofigure redirection of /redirect_me to another page
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
service nginx reload
