#!/usr/bin/env bash
# configure redirection of /redirect_me to another page
sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
header="\n\trewrite ^/rewrite_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s|listen 80 default_server;|&$header|g" /etc/nginx/sites-available/default
sudo service nginx restart
