#!/usr/bin/env bash
# configures a brand new ubuntu machine, set custom Nginx response header
# shellcheck disable=SC2059
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton school" > /var/www/html/index.nginx-debian.html
header="\n\tadd_header X-Served-By '$HOSTNAME';"
sed -i "s/listen 80 default_server;/&$header/g" /etc/nginx/sites-available/default
sudo service nginx restart
