#!/usr/bin/env bash
# configures a brand new ubuntu machine, set custom Nginx response header
# shellcheck disable=SC2059
apt -y update
apt -y install nginx
service nginx start
echo "Holberton school" > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
service nginx restart
service nginx reload
