#!/usr/bin/env bash
# This script create, delete a file and display some text when recieving signal
echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid' SIGQUIT SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
