#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" too if is 9
c=1
while [ $c -le 10 ]
do
    echo "Holberton School"
    if [ $c = 9 ]
    then
	echo "Hi"
    fi
    c=$(( c + 1))
done
